docs:
  enabled: true
  openapi_url: "{api_prefix}/openapi.json"
  docs_url: "{api_prefix}/docs"
  redoc_url: "{api_prefix}/redoc"
  swagger_ui_oauth2_redirect_url: "{api_prefix}/docs/oauth2-redirect"
  summary: "{{cookiecutter.project_summary}}"
  description: "{{cookiecutter.project_description}}"
  terms_of_service: "{{cookiecutter.term_url}}"
  contact:
    name: "{{cookiecutter.contact_name}}"
    email: "{{cookiecutter.contact_email}}"
    url: "{{cookiecutter.contact_url}}"
  license_info:
    name: "{{cookiecutter.license}} License"
    identifier: "{{cookiecutter.license}}"
    url: "https://opensource.org/licenses/{{cookiecutter.license}}"
  openapi_tags:
    - name: "Utils"
      description: "Useful utility endpoints."
  swagger_ui_parameters:
    syntaxHighlight.theme: nord
