services:
  api:
    image: bybatkhuu/rest.fastapi-template:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FT_API_PORT: ${FT_API_PORT:-8000}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:/var/log/rest.fastapi-template"
      - "api-data:/var/lib/rest.fastapi-template"
    ports:
      - "${FT_API_PORT:-8000}:${FT_API_PORT:-8000}"
    tty: true


volumes:
  api-logs:
  api-data:
