version: "3.8"

# services:
#   fastapi-template: # CHANGEME: Change service name
#     env_file:
#       - .env
#     deploy:
#       replicas: 0
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 512M
#     command: ["/bin/bash"]
#     command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port='${FASTAPI_TEMPLATE_APP__PORT:-8000}' --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log"]
