version: "3.8"

services:
  fastapi-template: # CHANGEME: Change service name
    image: ${IMG_NAMESCAPE}/fastapi-template:latest-gpu # CHANGEME: Change image name
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
    # env_file:
    #   - .env
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./app:/app/fastapi-template" # CHANGEME: Change project directory
      - "./volumes/.vscode-server:/home/fat-user/.vscode-server" # CHANGEME: Change user name
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port='${FASTAPI_TEMPLATE_APP_PORT:-8000}' --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"] # CHANGEME: Change env prefix
