version: "3.8"

services:
  fastapi-template: # CHANGEME: Change service name
    # env_file:
    #   - .env
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./fastapi_template:/app/fastapi_template" # CHANGEME: Change project directory
      - "./volumes/.vscode-server:/home/fat-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
