env: "LOCAL"
debug: false

api:
  name: "FASTAPI TEMPLATE REST API"
  slug: "rest.fastapi-template"
  bind_host: "0.0.0.0"
  port: 8000
  version: "1"
  prefix: "/api/v{api_version}"
  gzip_min_size: 1024 # Bytes (1KB)
  behind_proxy: true
  behind_cf_proxy: true
  dev:
    reload: false
    reload_includes: ["*.json", "*.yml", "*.yaml", "*.md", "*.html"]
    reload_excludes:
      [".*", "~*", ".py[cod]", ".sw.*", "__pycache__", "*.log", "logs"]
