api:
  paths:
    tmp_dir: "/tmp/{api_slug}"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "/var/lib/{api_slug}"
    security_dir: "{data_dir}/security"
    asymmetric_keys_dir: "{data_dir}/security/asymmetric_keys"
    # models_dir: "{data_dir}/models"
    # model_dir: "{data_dir}/models/{{model_id}}"
