api:
  paths:
    tmp_dir: "/tmp/{api_slug}"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "/var/lib/{api_slug}"
    credentials_dir: "{data_dir}/credentials"
    rsa_keys_dir: "{data_dir}/credentials/rsa_keys"
    # models_dir: "{data_dir}/models"
    # model_dir: "{data_dir}/models/{% raw %}{{model_id}}{% endraw %}"
