services:
  api:
    image: bybatkhuu/rest.fastapi-template:latest-gpu
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-all}
    volumes:
      - "./volumes/storage/rest.fastapi-template/logs:${FT_API_LOGS_DIR:-/var/log/rest.fastapi-template}"
      - "./volumes/storage/rest.fastapi-template/data:${FT_API_DATA_DIR:-/var/lib/rest.fastapi-template}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./src:/app/rest.fastapi-template"
      - "./volumes/.vscode-server:/home/ft-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${FT_API_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${FT_API_PORT:-8000}/api/v${FT_API_VERSION:-1}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
