docs:
  enabled: true
  openapi_url: "{api_prefix}/openapi.json"
  docs_url: "{api_prefix}/docs"
  redoc_url: "{api_prefix}/redoc"
  swagger_ui_oauth2_redirect_url: "{api_prefix}/docs/oauth2-redirect"
  summary: "FastAPI template project." # CHANGEME: Change project summary
  description: | # CHANGEME: Change project description
    FastAPI template project for building RESTful API services.

    ## Features

    - Markdown support
    - OpenAPI support
    - Swagger UI support
  terms_of_service: "https://example.com/terms"
  contact:
    name: "User Support"
    url: "https://example.com/contact"
    email: "user@example.com"
  license_info:
    name: "MIT License"
    identifier: "MIT"
    url: "https://opensource.org/licenses/MIT"
  openapi_tags:
    - name: "Utils"
      description: "Useful utility endpoints."
  swagger_ui_parameters:
    syntaxHighlight.theme: nord
